### ISSUE TITLE
Does not work with Notepad++ v.8.3.3 (only ever selects the current word)

### ISSUE THREAD

**Issue by Keyhabit** [ffes/selectquotedtext#3]
I think v.8.3 introduced some changes that affected plugins.

Any update would be much appreciated!

**Comment by ffes** [comment]
The fix is in the repository but not yet released. For now, you can download the working DLL from https://github.com/ffes/selectquotedtext/actions/runs/3192411041 and replace the one in the Notepad++ directory with this one.

**Comment by ghost** [comment]
> The fix is in the repository but not yet released. For now, you can download the working DLL from https://github.com/ffes/selectquotedtext/actions/runs/3192411041 and replace the one in the Notepad++ directory with this one.

expired

**Comment by ffes** [comment]
Fixed with released v1.1.0 at https://github.com/ffes/selectquotedtext/releases
